version: '2'
services:
  nginx:
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    expose:
      - "80"
  web:
    build: ./web
